INSERT INTO BENEFICIO (NOME, DESCRICAO, VALOR, ATIVO, VERSION) VALUES
('Vale Alimentação', 'Auxílio para compras em supermercados', 850.00, TRUE, 0),
('Vale Refeição', 'Auxílio para refeições diárias', 900.00, TRUE, 0),
('Plano de Saúde', 'Cobertura médica nacional', 1200.00, TRUE, 0),
('Plano Odontológico', 'Cobertura odontológica completa', 150.00, TRUE, 0),
('Auxílio Creche', 'Ajuda de custo para filhos até 5 anos', 450.00, TRUE, 0),
('Vale Transporte', 'Auxílio para deslocamento', 300.00, TRUE, 0),
('Auxílio Home Office', 'Ajuda de custo para internet e energia', 250.00, TRUE, 0),
('Gympass', 'Acesso a academias parceiras', 100.00, TRUE, 0),
('Seguro de Vida', 'Seguro de vida em grupo', 80.00, TRUE, 0),
('Bolsa Educação', 'Auxílio para cursos e graduação', 600.00, TRUE, 0),
('Participação nos Lucros', 'PLR anual', 5000.00, TRUE, 0),
('Auxílio Farmácia', 'Desconto em medicamentos', 50.00, TRUE, 0),
('Previdência Privada', 'Plano de aposentadoria complementar', 400.00, TRUE, 0),
('Auxílio Lente', 'Ajuda para compra de óculos de grau', 350.00, FALSE, 0),
('Day Off Aniversário', 'Folga remunerada no dia do aniversário', 0.00, TRUE, 0),
('Auxílio Casamento', 'Bônus para recém-casados', 1000.00, FALSE, 0),
('Licença Paternidade Estendida', '20 dias de licença paternidade', 0.00, TRUE, 0),
('Licença Maternidade Estendida', '6 meses de licença maternidade', 0.00, TRUE, 0),
('Auxílio Pet', 'Ajuda de custo para despesas veterinárias', 120.00, FALSE, 0),
('Bônus de Indicação', 'Bônus por indicação de novos talentos', 1500.00, TRUE, 0);
